### ISSUE TITLE
Add open graph tags to template.

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/tidytemplate#11]
So that package pages have previews, too… à la https://github.com/tidyverse/tidyverse.org/pull/123

**Comment by hadley** [comment]
Do you have thoughts on what is needed here? I'm going to take a pass at updating tidytemplate this week.

**Comment by batpigandme** [comment]
Yes,

**Comment by batpigandme** [comment]
So, the opengraph code from pkgdown _should_ work. I think…

https://github.com/r-lib/pkgdown/blob/923eea8c4379e200640a8c98578e82d335561478/inst/templates/head.html#L43-L52

<meta property="og:title" content="{{{pagetitle}}}" />
{{#opengraph}}
{{#description}}
<meta property="og:description" content="{{.}}" />
{{/description}}
{{#image}}
<meta property="og:image" content="{{{.}}}" />
{{/image}}
<meta name="twitter:card" content="summary" />
{{/opengraph}}

**Comment by batpigandme** [comment]
So, the opengraph code from pkgdown _should_ work. I think…

I'd (thought) I'd figured out a fix for it here https://github.com/tidyverse/tidytemplate/pull/12, but it borked the sizing of text in the header, IIRC, so we rolled it back.

My (admittedly stupid) sticking point was testing my local build, I basically can't figure out how to preview the changes since the styling comes from 

```

https://github.com/r-lib/pkgdown/blob/923eea8c4379e200640a8c98578e82d335561478/inst/templates/head.html#L43-L52

```
<meta property="og:title" content="{{{pagetitle}}}" />
{{#opengraph}}
{{#description}}
<meta property="og:description" content="{{.}}" />
{{/description}}
{{#image}}
<meta property="og:image" content="{{{.}}}" />
{{/image}}
<meta name="twitter:card" content="summary" />
{{/opengraph}}
```

**Comment by hadley** [comment]
I'm going to add a dummy function to tidytemplate so it can have its own website, which will hopefully make testing easier
