### ISSUE TITLE
Support development mode

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidytemplate#19]
- [ ] Link to dev documentation from navbar
- [x] Package version (only in dev?)
- [x] noindex meta information

**Comment by krlmlr** [comment]
For noindex:

https://github.com/r-lib/pkgdown/blob/b2798656f04ce282edea3e12734ba5588c6acd6e/inst/templates/head.html#L54-L55

**Comment by hadley** [comment]
New recommendation is use to 

```yaml
development:
  mode: auto
```

And then the linking from the navbar becomes a pkgdown problem, not a tidytemplate problem. (And in general, I'm not sure that every page should get a link to the dev version of the site)

**Comment by krlmlr** [comment]
How do we navigate to the dev version if the search engines only find the published version?

**Comment by krlmlr** [comment]
One way to handle this would be to link to the dev version from the GitHub page, e.g. https://tibble.tidyverse.org/ -> https://github.com/tidyverse/tibble -> 

![screenshot from 2018-09-15 14-49-25](https://user-images.githubusercontent.com/1741643/45586364-92410380-b8f6-11e8-8113-5d8ed1f6c74d.png)

(dev link here).

Or do we add the link to `DESCRIPTION` or to `_pkgdown.yml` ?

**Comment by krlmlr** [comment]
Added to _pillar_:

![screenshot from 2018-09-15 15-45-35](https://user-images.githubusercontent.com/1741643/45586919-7e010480-b8fe-11e8-9b29-b646f7e14633.png)

**Comment by hadley** [comment]
Please don't change these until we've had a chance to think it through and apply a principle consistently throughout the tidyverse.
