### ISSUE TITLE
Logo location?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidytemplate#2]
In light of the recent conversation about local images and READMEs, where should `logo.png` live?

For readxl, I just stowed it under `tools/`, following what I see in readr, but pkgdown assumes `logo.png` lives in package's top level directory. To get everything logo-related to work (present in index navbar, creation of favicon), I found I had to also place a copy of this file in top-level directory.

https://github.com/tidyverse/tidytemplate/blob/06b3af11d993ba3a723cb4830cb008e28e744811/inst/pkgdown/assets/tidyverse.css#L5827

**Comment by jennybc** [comment]
Also, the README/index.html of <http://tidyverse.org> assumes each package has `logo.png` in top level of its pkgdown website:

https://github.com/tidyverse/tidyweb/blame/2fc72a2fd4b2c85f3069437c3fd4a45ec060253f/README.Rmd#L36-L45

**Comment by hadley** [comment]
Fixed in pkgdown — it now copies to the top level for you
