### ISSUE TITLE
Mobile view doesn't show links and badges

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/tidytemplate#29]
on front page. Is this intended?

# Desktop view for _tibble_

![screenshot from 2018-09-15 15-01-31](https://user-images.githubusercontent.com/1741643/45586475-44c59600-b8f8-11e8-93e6-caf7bdcbd258.png)

# Mobile view

![screenshot from 2018-09-15 15-00-30](https://user-images.githubusercontent.com/1741643/45586480-4d1dd100-b8f8-11e8-89d3-c5f6338a3d22.png)

![screenshot from 2018-09-15 15-00-33](https://user-images.githubusercontent.com/1741643/45586482-50b15800-b8f8-11e8-9bb4-1dd7f4e211da.png)

**Comment by hadley** [comment]
Resolved in dev pkgdown
