### ISSUE TITLE
Figure out missing padding

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidytemplate#31]
https://dplyr.tidyverse.org/dev/index.html

**Comment by DavisVaughan** [comment]
[This line](https://github.com/tidyverse/tidytemplate/commit/5418a8d0ab31ca81a1e42834b13329a1180491f4#diff-e31cbb4cdb79ecb61c9b4413ab739be0L14) looks to be relevant and (from what I can see) did not make it into the revamped version. Adding just that `body{}` section to `tidyverse-2.css` seems to fix it for me. Not sure if [this chunk](https://github.com/tidyverse/tidytemplate/commit/5418a8d0ab31ca81a1e42834b13329a1180491f4#diff-e31cbb4cdb79ecb61c9b4413ab739be0L19) below it is also necessary.

**Comment by hadley** [comment]
Yes, they're both needed (the second one ensures that when you navigate to a heading it is shown, instead of being buried under the navbar)

But why does https://tidytemplate.tidyverse.org look ok?

**Comment by DavisVaughan** [comment]
After a bit of trial and error, it looks like both `yardstick` and `dplyr` currently have:

```
template:
  package: tidytemplate
  default_assets: false
```

Removing `defaults_assets: false` from `yardstick` and regenerating the docs with the dev version of `tidytemplate` (with no adjustments!) seems to work just fine.

**Comment by hadley** [comment]
Oh yeah, that's the change — maybe it's worth emphasising that in the readme.
