### ISSUE TITLE
top of content masked by navbar

### ISSUE THREAD

**Issue by espinielli** [tidyverse/tidytemplate#38]
Top section titles are not visible due to navbar masking them: for example in dplyr pkg page both "Overview" in the main section and "Links" in the sidebar are not visible.
Content should be "shifted down" to take into account of the navbar size.

In the screenshot below you can see that the header 2 (h2) containing the section title text "Overview" is masked by the navbar.

![screen shot 2019-01-07 at 9 43 45 am](https://user-images.githubusercontent.com/891692/50757853-d3bc3c80-1260-11e9-8f2f-175528de1045.png)

As an example of a possible solution (but maybe there is a better way), adding `margin-top: 60px` to the first `div` of class `row` solves the issue.

![screen shot 2019-01-07 at 9 55 14 am](https://user-images.githubusercontent.com/891692/50758441-89d45600-1262-11e9-8fae-df7308c112c4.png)

The issue has been spotted on both Chrome and Firefox.

**Comment by hadley** [comment]
I'm pretty sure this is now fixed
