### ISSUE TITLE
Template for (core) tidyverse only or also r-lib?

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/tidytemplate#4]
I've  noticed that [testthat](http://testthat.r-lib.org/index.html) (which is an r-lib package) has a tidyverse-like GitHub pkgdown Page and I was wondering whether [styler](https://github.com/r-lib/styler) should also use this template or whether it is only reserved for (as it says in the README) core tidyverse packages. If the latter is the case, are there any recommendations or / and guidelines on how the GitHub pkgdown Page of r-lib packages should look like? Maybe it would even make sense to adapt this template for r-lib packages so that it resembles the one for core tidyverse packages but the two are still distinguishable? 

Reference: https://github.com/r-lib/styler/issues/266

**Comment by hadley** [comment]
Yeah, we should probably have a specific r-lib style. We don't have much in the way of r-lib branding yet; will probably work on it later next year. In the meantime, I think it's probably better to use one of the default pkgdown styles (and testthat should probably do the same)

**Comment by lorenzwalthert** [comment]
Ok thanks.
