### ISSUE TITLE
Navbar is extending too far down on small screens

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidytemplate#42]
We haven't noticed this issue on any tidyverse packages (because their names are so short), but when the name of a package is long enough and the screen isn't very wide, you end up moving the `"part of tidymodels 0.0.1"` to the next line, which can cover up some of the screen, especially on mobile.

Here is what it looks like on a full screen laptop (all good here)

<img width="1680" alt="Screen Shot 2019-03-21 at 12 24 16 PM" src="https://user-images.githubusercontent.com/19150088/54767802-556f0580-4bd4-11e9-851e-5f74289ac175.png">

But when you shrink the screen really far you get...

<img width="402" alt="Screen Shot 2019-03-21 at 12 24 02 PM" src="https://user-images.githubusercontent.com/19150088/54767835-628bf480-4bd4-11e9-8563-0f00da1aa759.png">

Unfortunately, this is what it defaults to on most mobile screens because they aren't wide enough. Here is my iPhone 6s:

![IMG_6405](https://user-images.githubusercontent.com/19150088/54767992-ab43ad80-4bd4-11e9-9714-1136b7e55ec7.PNG)

Clearly I just need to choose shorter package names.

**Comment by dpprdan** [comment]
This also happens with tidyverse packages in the wild, see e.g. ggplot2 (Screenshot from Firefox on a Moto G5 plus (Full HD Screen)). 

![grafik](https://user-images.githubusercontent.com/1423562/57213956-a69e5180-6fe8-11e9-8a09-2f884e4ea63c.png)


With even longer package names, the "part of ..." text gets wrapped on a new line.


![grafik](https://user-images.githubusercontent.com/1423562/57214012-d0f00f00-6fe8-11e9-9fc5-ba5bea0a5cb4.png)

There are two issues IMO: 

1. better text wrapping in the navbar (or placing the "part of ..."/version text somewhere else)
2. making sure that the navbar does not cover the page text.

Is this something that could be fixed directly in pkgdown?

**Comment by jayhesselberth** [comment]
You could hide the `info` div on mobile classes, similar to what was done in https://github.com/r-lib/pkgdown/pull/932

Update this div:

https://github.com/tidyverse/tidytemplate/blob/27af8fd35dbba81d83e8b4a7e8677b8821fb8cc3/inst/pkgdown/templates/navbar.html#L14-L17

with:

```html
<div class="info hidden-xs hidden-sm">
```

**Comment by jayhesselberth** [comment]
Also we added [headroom to pkgdown](https://github.com/r-lib/pkgdown/pull/1032) so the navbar will disappear on mobile when scrolling.

**Comment by dpprdan** [comment]
@jayhesselberth headroom is only a partial solution IMO, like I mentioned in https://github.com/r-lib/pkgdown/pull/1041#issuecomment-496023781. But hiding the "part of ..." ought to work with the usual package name lengths.
