### ISSUE TITLE
Contrast in comments is low

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidytemplate#51]
e.g. https://dplyr.tidyverse.org/reference/arrange.html#examples

@dcossyleon do you have any ideas for a better treatment of comments? I want to make sure it's obviously output, not input, but I think the light grey background and dark grey text is a bit hard to read.

**Comment by dcossyleon** [comment]
Do you think a color change like this might make it better?

* lighter grey background
* green color comments (dark enough to still meets AA rating for accessibility)

![image](https://user-images.githubusercontent.com/29008894/94509038-562d2280-01e1-11eb-827f-1cc580f6f5c2.png)

* And maybe an additional bump in font-weight, like either of the images below
![image](https://user-images.githubusercontent.com/29008894/94509484-55e15700-01e2-11eb-8307-63644851185a.png)

![image](https://user-images.githubusercontent.com/29008894/94509551-7dd0ba80-01e2-11eb-81c6-20c77c7efd53.png)

**Comment by hadley** [comment]
Yeah, I like it!

**Comment by dcossyleon** [comment]
Great -- I will make these changes to tidyverse.css and merge in
