### ISSUE TITLE
How to fix `tidytemplate is not installed` in github pkgdown action?

### ISSUE THREAD

**Issue by vspinu** [tidyverse/tidytemplate#55]
I am getting this [error](https://github.com/tidyverse/lubridate/actions/runs/610705859) in lubridate pkgdown action.

I have looked at other tidyverse packages and they don't seem to be doing anything specific to install tidytemplate. What am I missing?

**Comment by hadley** [comment]
Looks like you resolved this so I'm going to close (and the latest GitHub actions install from `Config/needs/website` which is where we'll consistently put `tidyverse/tidytemplate` going forward)
