### ISSUE TITLE
Home page sidebar conflict with navbar

### ISSUE THREAD

**Issue by cderv** [tidyverse/tidytemplate#67]
This is how it looks
![image](https://user-images.githubusercontent.com/6791940/145203360-38bf3167-b854-48d6-8b20-a0a9a1a4be0c.png)

No issue on other page
![image](https://user-images.githubusercontent.com/6791940/145203442-d4c3fce4-f0fb-4698-8826-06f5f0fcfaaf.png)

I suppose this is a template issue as it doesn't happen with **pkgdown** itself

![image](https://user-images.githubusercontent.com/6791940/145203516-42400fac-4d66-44fb-bfa6-c0dbc5145912.png)

We have that in site using tidytemplate
![image](https://user-images.githubusercontent.com/6791940/145203553-a57da594-c373-4256-b157-4be2a112ada2.png)

![image](https://user-images.githubusercontent.com/6791940/145203590-49a90ec3-e4df-45c7-931a-756f927d3a9c.png)

**Comment by cderv** [comment]
It seems related to a conflict in CSS rules. 
aside is supposed to be taking account of navbar height
https://github.com/tidyverse/tidytemplate/blob/adcdac4a16ccea004763fb54ba1772b92636e24c/inst/pkgdown/BS5/extra.scss#L115-L117

However, two other rules got in the way 
![image](https://user-images.githubusercontent.com/6791940/145204561-39053072-bdf5-4463-8f8a-d9c3eaffa6b7.png)

For the other page, it works because it is taken into accound in #toc
https://github.com/tidyverse/tidytemplate/blob/adcdac4a16ccea004763fb54ba1772b92636e24c/inst/pkgdown/BS5/extra.scss#L110-L112

Probably the first two rules are Bootstrap rules ? 

We may need to add specificity to the current rule, or change the way it applies in aside. (like to as with #TOC for any first child into `<aside>` ?)

**Comment by gadenbuie** [comment]
You're right, we should increase the specificity of the [`aside` CSS rule](https://github.com/tidyverse/tidytemplate/blob/adcdac4a16ccea004763fb54ba1772b92636e24c/inst/pkgdown/BS5/extra.scss#L115-L117). At the very least the `margin-top` property needs to be applied to `.row > aside`.

Personally I'd prefer a rule that specifically targets `<aside>` elements in the content sidebar. 

- My first recommendation would be to ask pkgdown to add classes to the `<main>` and `<aside>` elements in the page content — e.g. `<main class="pkgdown-content">` and `<aside class="pkgdown-sidebar">`.
- Alternatively, to only change tidytemplate we could use `.container main + aside` which has both higher specificity and better targets the `<aside>` used by the sidebar

**Comment by gadenbuie** [comment]
@cderv Actually the problem can be resolved for quillt by adding

```yaml
template:
  bslib:
    pkgdown-nav-height: 77px
```

I still thing the tidytemplate `aside` rule should be made a little more specific. But also the tidytemplate CSS is probably a little out of date with the [recent changes to the pkgdown css](https://github.com/r-lib/pkgdown/compare/a8a962ad53d1eddf17f3def2f839221c07c04a32...9542e44#diff-42da929cc764e94ef6b729b3670bf1f2b086c8906ac4b67b8d0aefaba53133fa).

**Comment by hadley** [comment]
Sorry for missing this; I'll fix next year.
