### ISSUE TITLE
More padding needed between nav bar and LINKS in the top right

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidytemplate#69]
I think _technically_ the LINKS header isn't cutoff, but it could really use a little more padding between it and the nav bar

<img width="1679" alt="Screen Shot 2021-12-21 at 9 11 49 AM" src="https://user-images.githubusercontent.com/19150088/146943957-52df343f-d205-486e-ad3a-ddd75c3fcf5e.png">

**Comment by hadley** [comment]
Same as #67

**Comment by DavisVaughan** [comment]
Ooops, I read the description of that issue and thought it wasn't the same as this one. Sorry
