### ISSUE TITLE
Clicking on a TOC link in an article highlights the second above the one you clicked

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidytemplate#70]
I just clicked on "What does masking mean" and it brings you to the right section, but seems to highlight the one above it. It looks like non-tidytemplate sites don't have this problem.

https://rlang.r-lib.org/reference/topic-data-mask.html#what-does-masking-mean-

<img width="1679" alt="Screen Shot 2021-12-21 at 9 20 32 AM" src="https://user-images.githubusercontent.com/19150088/146945271-ccc62630-a57b-4a90-bfa8-9f0bda9df7d3.png">

i.e. compare to clicking on a TOC section here, which seems to highlight the one you clicked on
https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files

**Comment by hadley** [comment]
This is because of :

```js
    $('body').scrollspy({
      target: '#toc',
      offset: 56 // headroom height
    });
```

i.e. the scrollspy offset is fixed instead of using `pkgdown-nav-height`. This will need a fix in pkgdown.
