### ISSUE TITLE
Article TOC aren't expanding right if there are multiple levels

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidytemplate#72]
Before / after switch to BS5

<img width="1680" alt="Screen Shot 2021-12-21 at 10 22 44 AM" src="https://user-images.githubusercontent.com/19150088/146954999-86e6cedc-fbc4-4b79-9e17-441460552af7.png">

<img width="1680" alt="Screen Shot 2021-12-21 at 10 23 03 AM" src="https://user-images.githubusercontent.com/19150088/146955018-c026fe48-e3aa-4e96-95d4-719447805e51.png">

Seems to be a tidy template issue. Compare to pkgdown's article https://pkgdown.r-lib.org/articles/customise.html#theming

**Comment by hadley** [comment]
This may be a pkgdown bug, but the easiest fix is you use `<h2>` for the body headings instead of `<h1>`
